### ISSUE TITLE
example.py is not running

### ISSUE THREAD

**Issue by ai-quantitative** [aljubrmj/FGEM#1]
Some missing files or wrong path?

File "C:\Users\gmoog\anaconda3\envs\fgem-env\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/battery.csv'

config.json references a few others as well. like wholesale.csv, capacity.csv....that aren't readily apparent when doing a search in the project's folder.

**Comment by aljubrmj** [comment]
Good call! `example.py` is actually outdated and misplaced, so it is now removed. Please refer to the [examples dir](https://github.com/aljubrmj/FGEM/tree/main/examples) for sample configurations and runs in Jupyter Notebooks. Going forward, we plan to make these scripts in `.py` python scripts for package testing.
